library(dplyr)
data = read.table("./householddata/household_power_consumption.txt",header=TRUE,sep=";")
req_data = filter(data,Date == "1/2/2007" | Date=="2/2/2007")
t = paste(req_data$Date,req_data$Time)
t = strptime(t,"%d/%m/%Y %H:%M:%S")
ans <- req_data %>%
  mutate(Date = t)
png("plot3.png")
plot(ans$Date,as.numeric(ans$Sub_metering_1), type="l", ylab = "Energy sub metering",xlab="")
lines(ans$Date,as.numeric(ans$Sub_metering_2), type="l", ylab = "Global Active Power (kilowatts)",xlab="",col="blue")
lines(ans$Date,as.numeric(ans$Sub_metering_2), type="l", ylab = "Global Active Power (kilowatts)",xlab="",col="red")
lines(ans$Date,as.numeric(ans$Sub_metering_3), type="l", ylab = "Global Active Power (kilowatts)",xlab="",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch = "-",text.col = c("black","red","blue"))
dev.off()